name: ssh-action-uwu
description: 'Run commands on your vps after deploy'
author: 'sebastianjnuwu'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  LOGIN:
    description: ''
    required: true
  KEY:
    description: ''
    required: true
  RUN: 
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🗿 Setting up ssh...
      run: |
        mkdir /root/.ssh
        echo "${{ inputs.KEY }}" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        
      shell: bash
    - name: 🍷 Executing commands...
      run: ssh -o StrictHostKeyChecking=yes "${{ inputs.LOGIN }}" "${{ inputs.RUN }}; exit"
      shell: bash
