name: ssh-action-deploy
description: "Deploy has never been so easy, running commands has never been simpler..."
author: "sebastianjnuwu"
branding:
  icon: "terminal"
  color: "purple"

inputs:
  IP:
    description: "A unique identifier for a device on the Internet or a local network."
    required: true
  USER:
    description: "An agent, which can be a human or software agent, using a computer or network service."
    required: true
  KEY:
    description: "A component of the Secure Shell protocol suite used to establish secure shell sessions between remote computers over insecure networks, using cryptographic techniques."
    required: true
  REPO:
    description: "The name of the repository where the action is located (default: the GitHub repository)."
    default: ${{ github.repository }}
  FOLDER:
    description: 'The name of the folder where files are located, including the user (e.g., "/user/deploy").'
    required: true
  RUN:
    description: "Commands to be executed after the deploy (optional)."
    required: false


runs:
  using: "composite"
  steps:
    - name: ðŸ—¿ Creating ssh files...
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.KEY }}" > ~/.ssh/ssh.key
        chmod 600 ~/.ssh/ssh.key
      shell: bash
    - name: ðŸ· Setting the ssh Key...
      run: |
        cat >>~/.ssh/config <<END
        Host ssh
          HostName ${{ inputs.IP }}
          User ${{ inputs.USER }}
          Port 22
          IdentityFile ~/.ssh/ssh.key
          StrictHostKeyChecking no
        END
      shell: bash
    - name: âœ¨ Removing old files...
      run: |
        ssh ssh rm -rf "${{ inputs.FOLDER }}";
      shell: bash
    - name: ðŸ’§ deploy to vps...
      run: |
        cd ..
        IN="${{ inputs.REPO }}"
        set -- "$IN" 
        IFS="/"; declare -a Array=($*) 
        scp -r ${Array[1]} ssh:/${{ inputs.FOLDER }}
      shell: bash
    - name: ðŸ· Executing commands...
      if: ${{ inputs.RUN }}
      run: ssh ssh "${{ inputs.RUN }}"
      shell: bash
