name: ssh-action-deploy
description: 'Deploy has never been so easy running commands even less...'
author: 'sebastianjnuwu'
branding:
  icon: 'terminal'
  color: 'purple'

inputs:
  IP:
    description: 'IP address is a unique address that identifies a device on the Internet or on a local network.'
    required: true
  USER:
    description: 'A user or user is an agent, either a human agent or a software agent, who uses a computer or network service.'
    required: true
  KEY:
    description: 'ssh-keygen is a standard component of the Secure Shell protocol suite found on Unix, Unix-like and Microsoft Windows computer systems used to establish secure shell sessions between remote computers over insecure networks, through the use of various cryptographic techniques. '
    required: true
  REPO:
    description: 'Put the name of the repository where the action is.'
    default: ${{ github.repository }}
  FOLDER:
    description: 'Name of the folder where the files are located.'
    required: true
  RUN: 
    description: 'Put the commands that will be executed after the deploy.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: ðŸ—¿ Creating ssh files...
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.KEY }}" > ~/.ssh/ssh.key
        chmod 600 ~/.ssh/ssh.key
      shell: bash
    - name: ðŸ· Setting the ssh Key...
      run: |
        cat >>~/.ssh/config <<END
        Host ssh
          HostName ${{ inputs.IP }}
          User ${{ inputs.USER }}
          Port 22
          IdentityFile ~/.ssh/ssh.key
          StrictHostKeyChecking no
        END
      shell: bash
    - name: âœ¨ Removing old files...
      run: |
       ssh ssh rm -rf /${{ inputs.FOLDER }}
      shell: bash 
    - name: ðŸ’§ deploy to vps...
      run: |
       cd ..
       IN="${{ inputs.REPO }}"
       set -- "$IN" 
       IFS="/"; declare -a Array=($*) 
       echo "${Array[1]}"
      shell: bash 
    - name: ðŸ· Executing commands...
      run: ssh ssh "${{ inputs.RUN }}"
      shell: bash
